plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    alias(libs.plugins.spotless)
    alias(libs.plugins.errorprone)
}

group = 'com.solarianofc'
version = '0.0.1-SNAPSHOT'
description = 'GameService'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation libs.jspecify
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    errorprone libs.errorprone.core
    errorprone libs.nullaway
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-Werror'
}

tasks.named('compileJava') {
    options.errorprone {
        error('NullAway')
        option('NullAway:OnlyNullMarked', 'true')
        option('NullAway:JSpecifyMode', 'true')
    }
}

tasks.named('compileTestJava') {
    options.errorprone.disable('NullAway')
}

tasks.named('test') {
    useJUnitPlatform()
}

spotless {
    java {
        target 'src/**/*.java'
        palantirJavaFormat(libs.versions.palantir.java.format.get())
    }
}
