spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gameservice
    username: gameservice
    password: gameservice
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
